<?php
function dss_betamessage_page_top(array &$page_top) {
  //Get Config vals
  $config = \Drupal::config('dss_betamessage.credentials');
  $attachto = $config->get('attach_to');
  $messagewords = $config->get('messagewords');
  $theme = $config->get('theme');
  $tag = $config->get('tag');
  // Add the library and the #markup into page_top
  $page_top['dss_betamessage'] = [
    '#attached' => [
        'library' => ['dss_betamessage/dss-betamessage'],
        'drupalSettings' => array(
          'dss_betamessage' => array(
            'theme' => $theme,
            'tag' => $tag,
          ),
        ),
      ],
    '#markup' => '<p id="betamessage" class="betamessage betamessage-'.$theme.'" data-attach-to="'.$attachto.'" aria-label="'.$tag.' site message" role="group">
      <span class="betamessage-text"><span class="betamessage-tag betamessage-'.$tag.'" aria-hidden="true">'.$tag.'</span>'.$messagewords.'</span>
      <span class="betamessage-close"><a href="#" aria-label="Hide this message">Hide this</a></span>
      </p>',
  ];
}
